start.sh

Adds a basic shell script for activating the venv and starting the API - it requires the user to have already installed the pre-requisites in venv.

Add start-up shell script for Linux

---

OAI/types/chat_completion.py
OAI/types/common.py
OAI/types/completion.py
OAI/utils.py
auth.py
main.py
model.py
utils.py

Out of the 4 methods of using the API (completion, completion+streaming, chat, chat+streaming), the usage stat was not added to streaming version of the chat. That's because unlike the other 3, this one's response class did not have the usage stat's place holder. So I was not sure if that response is supposed to have it. Adding the support to that response is fairly easy, if needed.

Adding the usage stat support (prompt_tokens, completion_tokens, and total_tokens)

---

model.py

Enables automatic calculation of NTK-aware alpha scaling for models if the rope_alpha arg is not passed in the config, using the same formula used for draft models. This uses the model's max seq length as defined in config.json and compares it to the configured max sequence length passed to the API (or through config.yml) to determine the ratio used to calculate alpha.
Note: If the model's max seq length and the configured max seq length are the same, the alpha calculated via the existing formula is ~0.96 rather than 1. Open to suggestion on whether we force alpha = 1 in this case.

Add automatic NTK-aware alpha scaling to model

---

OAI/types/model.py

When performing a model load request, the draft rope parameters are by default set to 1.0
```
class DraftModelLoadRequest(BaseModel):
draft_model_name: str
draft_rope_alpha: float = 1.0
draft_rope_scale: float = 1.0
```
The problem is that at least in the case of draft model alpha scaling, the draft_rope_alpha can never be None so the draft_rope_alpha is never auto calculated.
```
self.draft_config.scale_pos_emb = unwrap(draft_args.get("draft_rope_scale"), 1.0)
self.draft_config.scale_alpha_value = unwrap(draft_args.get("draft_rope_alpha"), self.calculate_rope_alpha(self.draft_config.max_seq_len))
```
By setting the draft model request parameters as optional then the unwrap can function as intended

OAI: adding optional draft model properties for draft_rope alpha and scale

---

model.py
templating.py

The chat templates that I've seen are usually listed in the `tokenizer_config.json`. This MR opens the `tokenizer_config.json` in the model directory if it exists, loads the json, checks for the `"chat_template"` property, if it exists return a `ChatTemplate` otherwise return None.
This function follows the same pattern as the model config check for `chat_template`

Templates: Added automatic detection of chat templates from tokenizer_config.json

---

templating.py

During refactoring of get_template_from_model_json a method invocation was converted to a property check, the exists method invocation is missing the `()`
`if json_path.exists:` which should be `if json_path.exists():`

Templates: fixed method invocation in get_template_from_model_json

---

auth.py
gen_logging.py
logger.py
main.py
model.py
requirements-amd.txt
requirements-cu118.txt
requirements-nowheel.txt
requirements.txt
tests/wheel_test.py
utils.py

This PR switches all print statements to proper logging. I'm also adding a small dependency on `colorlog` (11kb and no external dependencies).

feat: logging

---

requirements-amd.txt

This addresses the following error when using the `requirements-amd.txt` file and Python 3.11:
```
ERROR: exllamav2-0.0.11+rocm5.6-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.
```

Only try to install one of the EXLv2 wheels

---

OAI/types/chat_completion.py
OAI/types/common.py
OAI/types/completion.py
OAI/utils/completion.py
backends/exllamav2/model.py
common/sampling.py
main.py

Adds logprobs support to upstream tabby for completions and chat completions

Logprobs support

---

backends/exllamav2/model.py
backends/exllamav2/utils.py
requirements-amd.txt
requirements-cu118.txt
requirements.txt

**Description**
Change logits to return post-sampling vs pre-sampling to accurately represent the correct percentages.
Also switch the generator to use the streaming_ex gen which returns a more flexible dictionary.
Blocking on release of exllamav2 v0.0.13.post2

Switch over logprobs to work with post-sampling

---

backends/exllamav2/grammar.py
backends/exllamav2/model.py
common/sampling.py

Adds support for constraining generation to a certain output. This PR will add the following:
- Fast and accurate JSON constrained generation via [JSON schemas](https://json-schema.org/): [lm-format-enforcer](https://github.com/noamgat/lm-format-enforcer)
- Basic EBNF support: [Outlines](https://github.com/outlines-dev/outlines)
Notes:
- JSON schemas are a standardized format for declaring the properties of a JSON. It's extendable and easy to use. There are websites that allow for schema creation such as [JsonGenerator](https://www.jsongenerator.io/schema)
- Outlines isn't exactly the fastest library out there but provides EBNF support that can be hooked into ExllamaV2. Eventually, this will be replaced by a more flexible in-house solution.

[FEAT] Constrained generation/Grammar

---

config_sample.yml

In discussion with multiple users in support threads, new users frequently incorrectly use override_base_seq_len instead of max_seq_len to configure context length. This will cause problems if they attempt to use the built in automatic NTK rope scaling for context extension.
Also the documentation incorrectly specifies Mixtral as an example model with an incorrect base sequence length, when this only applies to Mistral 7B with sliding window attention inactive in exl2.
It will lead to fewer users using incorrect configurations.
**Examples**
None
None

Additional clarification for override_base_seq_len

---

OAI/types/lora.py
OAI/types/model.py
backends/exllamav2/model.py
common/auth.py
common/generators.py
common/utils.py
main.py

Fixes a lot of issues with the API in terms of parallel requests and what specifically goes into the "request queue" (aka a semaphore). These commits help preserve the parallelism for single users and make the queueing system for multiple users (e.g 2-5 people).
The new request/semaphore architecture will be like this
- Any load requests are blocked by the semaphore to be processed sequentially
- Any load request can have the `skip_queue` parameter which bypasses the semaphore and immediately executes the request.
- Any unload requests are immediately executed
- All completion requests get placed inside the semaphore
More optimizations are needed in the future for extra cases, but I'd like to do other things to make the API code cleaner beforehand.
This is a good starting point/bugfix for …

[FEAT] Add extra concurrency to API

---

docker/Dockerfile

These packages are already installed via `requirements.txt`.

Remove explicit install of pytorch & exllamav2 in Dockerfile

---

backends/exllamav2/model.py
common/concurrency.py
common/model.py
common/signals.py
common/utils.py
endpoints/OAI/app.py
endpoints/OAI/utils/chat_completion.py
endpoints/OAI/utils/completion.py
endpoints/OAI/utils/lora.py
endpoints/OAI/utils/model.py
main.py

Previously, the API used a lot of thread hacks to work properly. This involved spawning the API itself on a separate thread which is extremely unideal. Instead, opt for an async first approach and add synchronous workflows as needed.
This change adopts exllamav2's synchronous nature with tabby's async-first principle, allowing for the ability to implement task-based calls in the future which are also easily cancellable. In addition, fix a few more API problems involving loading and signal handling.
This change is probably the closest to async that I can get without rewriting exllamav2 itself or making a full async wrapper. There are still threads being used here, but it's used in a more conventional method of "running stuff in the background" rather than "running the event loop inside a …

Make API more asynchronous

---

pyproject.toml

The pyproject.toml file does not have the correct exllamav2 assembly for cuda 11.8

Fix: the link to the exllamav2 build for cuda 11.8

---

backends/exllamav2/model.py
common/sampling.py
sampler_overrides/sample_preset.yml

`min_tokens`:
Bans the EOS token until the generation reaches a minimum length. This will not prevent the model from otherwise ending the generation early by outputting other stop conditions.
I did not add validation for this arg because improper values for `min_tokens` should not cause any errors or aberrant behavior. Negative values will function the same as zero, and values greater than `max_tokens` will function as a full EOS ban.
`banned_strings`:
From exllamav2: List of strings that the generator will refuse to output. As soon as a partial match happens, a checkpoint is saved that the generator can rewind to if need be. Subsequent tokens are then held until the full string is resolved (match or no match) and either emitted or discarded, accordingly.
Both require exllamav2 dev with …

Add support for min_tokens and banned_strings

---

backends/exllamav2/model.py

`banned_strings` is never added to `begin_stream_args`, so it's never passed into the `begin_stream_ex` call, and thus doesn't do anything.
This PR just adds it in.
Edit: `decode_special_tokens` was missing as well

Fix: Actually pass banned_strings to the generation call.

---

backends/exllamav2/grammar.py
backends/exllamav2/model.py
common/sampling.py

Adds the ability to constrain generation via regex pattern using `lm-format-enforcer`, expanding on the existing functionality to constrain via JSON schema.
N/A
This allows the generation to be constrained via regex, which is arguably simpler to use than EBNF grammar.
**Examples**
N/A
N/A

Add support for regex pattern constraints

---

backends/exllamav2/grammar.py
backends/exllamav2/model.py
backends/exllamav2/utils.py
common/concurrency.py
common/downloader.py
common/gen_logging.py
common/model.py
common/sampling.py
config_sample.yml
endpoints/OAI/router.py
endpoints/OAI/types/model.py
endpoints/OAI/utils/chat_completion.py
endpoints/OAI/utils/completion.py
endpoints/OAI/utils/model.py
pyproject.toml

Dependency compat upgrade
Adds support for ExllamaV2's dynamic generator which handles prompt processing and multi-user management internally.
Resolves #77, #98, #107

Dynamic Generator

---

backends/exllamav2/model.py
common/args.py
config_sample.yml
endpoints/OAI/types/model.py

In order to use CFG at full context length, the user needs to be able to specify a k/v cache size greater than `max_seq_len`.
In order to use CFG at full context length, the user needs to be able to specify a k/v cache size greater than `max_seq_len`. This also allows the user to make full use of their available VRAM for increasing batch size or increasing the number of cached prompts.
**Examples**
N/A
N/A

Add support for specifying k/v cache size

---

backends/exllamav2/model.py
common/gen_logging.py

The prompt processing metrics currently do not take into account how many tokens of the prompt are being reused from cache versus having to be newly processed, leading to misleadingly large numbers when a majority if the prompt is already cached.
This provides more detail regarding how many tokens are reused from cache for each generation, and measures prompt processing speed only on new prompt tokens.
**Examples**
N/A
The metrics displayed will not be correct until https://github.com/turboderp/exllamav2/commit/ff79b73e82aeb5623214620758fedb42eebb59e9 is merged to exllamav2 master.
Prompt processing T/s may also not be very accurate when there is a small number of …

Separate new prompt tokens from those reused from cache in metric logging

---

endpoints/OAI/types/common.py
endpoints/OAI/utils/chat_completion.py
endpoints/OAI/utils/completion.py
pyproject.toml

See #110 
Adds the "n" parameter to the OAI api which allows for multiple choices to be returned at once. This is streamed in asynchronous chunks when streaming is enabled and waited in non-streaming.

Add the "n" parameter to the OAI API

---

endpoints/OAI/types/chat_completion.py
endpoints/OAI/utils/chat_completion.py

This PR is related to [issue116](https://github.com/theroyallab/tabbyAPI/issues/116), [issue117](https://github.com/theroyallab/tabbyAPI/issues/117) and [QChatGPT/issue798](https://github.com/RockChinQ/QChatGPT/issues/798).
OAI API now supports following two kinds of `messages.*.content` in `ChatCompletionRequest`, as the [reference doc](
https://platform.openai.com/docs/api-reference/chat/create)
OAI official API supports this case, and some client will not convert the text-only array to a string automatically.
As OpenAI API reference develops, more and more GPT related apps will follow the new API standard. And at that time, tabbyAPI would be outdated.
In the given context below:
```json
{
"model": "gpt-3.5-turbo",
"messages": [
{
"role": "system",
"content": "You are a helpful …
```

Support List type in `messages.content`

---

backends/exllamav2/utils.py
pyproject.toml

N/A
v0.1.4 fixes a number of issues, mostly related to Q4 cache mode.
**Examples**
N/A
N/A

Bump exllamav2 to 0.1.4

---

backends/exllamav2/grammar.py

Fix for #127
Allows first character of JSON completion to be either "[" or "{", preventing "Filter excluded all tokens" error when the JSON schema defines a top-level array.
**Examples**
N/A
Requires exllamav2>=0.1.4

[fix] Allow multiple prefixes with JSON constraint

---

backends/exllamav2/model.py

Multiple users have encountered errors when Tabby attempts to enable paged mode, but some part of their configuration doesn't support it, as Tabby currently only checks for whether the user's GPUs have the compute capability to run flash attention 2.
This PR performs the following checks in order:
1. Disable paged mode if the user passes `no_flash_attention = True`
2. Disable paged mode and flash attention if any of the user's in-use GPUs does not have compute capability for flash attention 2
3. Disable paged mode and flash attention if flash attention is not installed, and instruct user to install
4. Disable paged mode if flash attention version < 2.5.7, and instruct user to update …

More extensive checks for paged mode support

---

backends/exllamav2/model.py

Users who do not specify a `cache_size` manually will end up with a default cache that is too small for CFG.
This warns the user that they should set the `cache_size` to at least `2 * max_seq_len` to avoid running out of pages when prompting with CFG.
**Examples**
N/A
This will warn the user that https://github.com/theroyallab/tabbyAPI/issues/119 may occur.

Warn if cache size is too small for CFG

---

backends/exllamav2/model.py
backends/exllamav2/utils.py
config_sample.yml
endpoints/OAI/types/model.py
pyproject.toml

No prebuilt wheels were provided for Python 3.12.
Provides prebuilt wheels for Python 3.12.
**Examples**
N/A
N/A

Update dependencies, support Python 3.12, update for exl2 0.1.5

---

backends/exllamav2/model.py

Paged mode was being correctly disabled for unsupported setups, however exllamav2 requires that flash attention also be manually disabled for unsupported configurations even when falling back to compatibility mode.
Resolves https://github.com/theroyallab/tabbyAPI/issues/135
**Examples**
N/A
This has the side effect of disabling flash attention for users with `2.2.1 <= flash-attn version < 2.5.7` to avoid additional checks. This was felt to be acceptable as all setups that support `flash-attn >= 2.2.1` will also support `flash-attn >= 2.5.7` and users will be prompted to upgrade.

Fix disabling flash attention in exl2 config

---

backends/exllamav2/model.py

If v1/model/load is cancelled:
ERROR:    Model load cancelled by user. Please make sure to run unload to free up resources.
then the next call to v1/model/load throws during cleanup, since self.generator is None:
```
Traceback (most recent call last):
File "tabbyAPI/endpoints/OAI/utils/model.py", line 50, in stream_model_load
async for module, modules, model_type in load_status:
File "tabbyAPI/common/model.py", line 47, in load_model_gen
await unload_model()
File "tabbyAPI/common/model.py", line 27, in unload_model
await container.unload(skip_wait=skip_wait)
File "tabbyAPI/backends/exllamav2/model.py", line 742, in unload
await self.generator.close()
ERROR:    AttributeError: 'NoneType' object has no attribute 'close'
```

Fix exception unloading models.

---

backends/exllamav2/grammar.py
backends/exllamav2/model.py

Slow initialization of constrained requests due to each request recreating the same instance of LMFE's tokenizer data class, which is a slightly expensive operation.
Fixes the above by caching the tokenizer data.
**Examples**
N/A
N/A

Tokenizer data fix

---

endpoints/OAI/types/chat_completion.py
endpoints/OAI/types/common.py
endpoints/OAI/utils/chat_completion.py

It's currently impossible to get usage information when using tabby in streaming mode. This PR fixes that by implementing support for the `stream_options` argument from openai API.

Support stream_options argument to get usage info in streaming mode

---

api_tokens_sample.yml
docker/.dockerignore
docker/Dockerfile
docker/docker-compose.yml

This PR improves the docker workflow for deploying tabbyAPI. It moves the deployment configuration outside the docker image. This allows us to change the deployment configurations such as model, host and port without having to rebuild the docker image.
Additionally, I create a sample for `api_tokens.yml` named  `api_tokens_sample.yml`. This makes it easier for new users to understand how to persist their auth tokens.
It makes working with docker a lot easier
**Wiki**
The [wiki](https://github.com/theroyallab/tabbyAPI/wiki/1.-Getting-Started#docker) should be updated to account for the changes. Suggested version:
Docker
1. Install Docker and docker compose from the …

Improve docker deployment configuration

---

.github/workflows/docker-image.yml

Solves https://github.com/theroyallab/tabbyAPI/issues/123 and https://github.com/theroyallab/tabbyAPI/issues/169#issuecomment-2299042703
Currently, we have to clone the code and build the docker image. This requires:
1. Docker
2. Building the image (takes a lot of resources)
To make it easier for developers to setup and run tabbyAPI quickly.
**Examples**
Check the published [images](https://github.com/AmgadHasan/tabbyAPI/pkgs/container/tabbyapi/versions) on my fork.
None

Build and push docker image

---

common/auth.py
docker/docker-compose.yml
endpoints/core/router.py

Adds:
- localhost only /healthcheck endpoint
- cURL healthcheck in docker compose file
A healthcheck allows the docker daemon to restart tabbyAPI in case of a crash
**Examples**
If the tabbyAPI server crashes and hangs indefinitely then docker will not restart the application without a health check

Add healthcheck

---

backends/exllamav2/model.py
common/args.py
common/model.py
config_sample.yml
endpoints/OAI/router.py
endpoints/core/types/model.py
endpoints/core/utils/model.py

Currently, setting up a model configuration can be difficult for users since many parameters are hard to understand and a model's `config.json` is unreadable and rarely modified.
This feature adds support for users and model developers to add a `tabby_config.yml` file which provides an extra configuration layer for load parameters.
Any key from the `model` block of config.yml is supported in this file. So, draft model overrides are possible as well.
For example, Llama 3.1 has a max_seq_len of 128000 by default unless otherwise specified in either the API request or the user's config.yml file. Now, a user can add a `tabby_config.yml` file in the model folder which has the line …

Override default model load parameters via yaml

---

backends/infinity/model.py

- additional logging
- changed declaration order prevents has_infinity_emb becoming undefined when there are errors other then import error
- added additional type hinting
**Examples**
The software is more likely to crash without these changes if there is an issue with the infinity embed backend
completes a TODO in the code

Complete conditional infinity import TODO

---

docker/docker-compose.yml

- Docker compose uses the prebuilt images produced by the GitHub action added in 872eeed581380ae032dfc039479934ce9a55e6f3
There are prebuilt docker images that are known to work provided by the existing github action. It seems reasonable to use them by default instead of having every end user duplicate the effort and compile their own image.
Benefits include:
- lower start-up time
- lower initial complexity for end users
- no requirement to clone the git repo

make docker-compose use prebuilt images

---

endpoints/OAI/utils/completion.py

In the exception text, "inline_model_load" should instead spell "inline_model_loading".
Invalid config references confuses the user.
**Examples**
Try to load the model without "inline_model_loading" set to true. Observe the error.
None.

Properly specify config "inline_model_loading" value in the error message

---

.dockerignore
docker/.dockerignore
docker/Dockerfile

- decrease container size
- decrease potential attack surfaces
- faster build time
**Examples**
tests are not required in a production container

debloat docker build

---

.github/workflows/pages.yml
.gitignore
backends/exllamav2/model.py
common/actions.py
common/args.py
common/auth.py
common/config_models.py
common/downloader.py
common/gen_logging.py
common/model.py
common/networking.py
common/sampling.py
common/tabby_config.py
common/utils.py
config_sample.yml
endpoints/OAI/router.py
endpoints/OAI/utils/completion.py
endpoints/core/router.py
endpoints/core/types/model.py
endpoints/core/utils/model.py
endpoints/server.py
main.py
pyproject.toml

This PR rewrites the configuration logic to be a subclass of a pydantic model. This has the following benefits:
- type validation for all models
- single source of truth for all configuration options
- automatically generate template config files
- improve type hinting and static analysis
- remove ambiguity with unknows relating to kwargs
- remove the need for many unwrap() calls
When a new config option is added to the pydantic models:
- automatically add new command line arguments
- automatically add new environment variables
- automatically add support inside of config.yml
Possible benefits in the future:
- generate a new config file from the current config at the time of an error to improve debugging
- generate a new config.yml file with new additions while retaining the current …

Pydantic config

---

.github/workflows/pages.yml
backends/exllamav2/utils.py
backends/exllamav2/version.py
backends/infinity/model.py
common/actions.py
common/model.py
common/optional_dependencies.py
endpoints/utils.py
main.py

This PR creates a separate pydantic model for managing the state of optional dependencies, so that it is easy to check what is installed.
It also removes the dependency on pytorch/exl2 from the main.py file so that all actions can be triggered without the need to install optional dependencies. This significantly speeds up the functions for generating a config file or generating an openapi.json schema.

fix issues with optional dependencies

---

backends/exllamav2/model.py
common/health.py
endpoints/core/router.py
endpoints/core/types/health.py

Recently when hibernating my PC I experienced the model unloading and tabbyAPI getting itself stuck reloading the EXL2 container every request.
This issue adds an internal logging system for fatal errors and code to auto generate a response for the health check endpoint so that it is possible to automatically restart the program if this happens again and fix the error
**Examples**
The health check endpoint returns 200 OK and status healthy on my machine even when every request is responded to with an error. This would fix that. 
In the future it will be possible to expand this system easily if more possible fatal errors are discovered by adding a statement to …

Add health check monitoring for EXL2 errors

---

common/sampling.py
common/tabby_config.py
common/utils.py

An incorrect dictionary key meant that `--config <file.yml>` was broken

fix config file loader

---

backends/exllamav2/model.py
endpoints/OAI/utils/completion.py
endpoints/core/router.py
endpoints/core/types/model.py
endpoints/core/types/template.py
endpoints/core/utils/model.py
main.py

Bypasses template:
Fix inline load with draft models and rename the provided key internally to be consistent.

Model: Fix inline loading and draft key

---

backends/exllamav2/model.py
common/sampling.py
common/transformers_utils.py
endpoints/Kobold/router.py
endpoints/Kobold/types/generation.py
endpoints/Kobold/utils/generation.py
endpoints/OAI/types/common.py
endpoints/OAI/utils/chat_completion.py
endpoints/OAI/utils/completion.py
endpoints/server.py

This PR aims to refactor parts of the sampling to be much more compact.

Refactor the sampling class

---

backends/exllamav2/model.py

Fixes https://github.com/theroyallab/tabbyAPI/issues/238
N/A
**Examples**
N/A
Flash attention was not being disabled for the draft model after being determined to be unavailable/incompatible.

Fix draft model non-FA2 fallback

---

backends/exllamav2/model.py

Fixes https://github.com/theroyallab/tabbyAPI/issues/240
N/A
**Examples**
N/A
TabbyAPI was calculating `chunk_size` to be a value >= 16 and <= `max_seq_len`, however exllamav2 requires this to be a multiple of 256.

Enforce chunk_size as multiple of 256

---

endpoints/OAI/utils/chat_completion.py

Related to #234.
Not a proper fix, but could be merged into a local branch if anyone needs a quick workaround.
**Examples**
Enables tool calling again. However, it still raises an error when combined with draft models. To work around that background_drop should be called early. I'm having a hard time understanding the code in the time I have, and SD+TC is probably only wanted by a few people, so this is all I have for now.
I tried disabling the draft model just before generating the prompt for the tool call (mainly to not have to relaunch TabbyAPI to switch from using a draft for coding and back to using tool calling), but I got into a tool call loop. That's not the …

workaround for tool calling

---

backends/exllamav2/grammar.py
backends/exllamav2/model.py
pyproject.toml

N/A
Simplify dependencies and improve grammar-constrained inference performance.
**Examples**
N/A
To-do:
Other:

Switch grammar backend to Formatron

---

backends/exllamav2/model.py

Intended to prevent https://github.com/theroyallab/tabbyAPI/issues/251 from occurring due to more robustly validating generation parameters.
- Ensure that length of positive/negative prompt + max_tokens does not exceed max_seq_len
- Ensure that total required pages for CFG request does not exceed allocated cache_size
**Examples**
N/A
N/A

Robust request length checking in generator

---

pyproject.toml

Fixes issue with tool calling, where a completion request was always crashing due to:
```
"/usr/local/lib/python3.10/dist-packages/formatron/formatter.py", line 388, in
to_json
ERROR:        if isinstance(schema, type) and issubclass(schema, Schema):
ERROR:      File "/usr/lib/python3.10/abc.py", line 123, in __subclasscheck__
ERROR:        return _abc_subclasscheck(cls, subclass)
ERROR:    TypeError: issubclass() arg 1 must be a clas
```
It was fixed (thanks @Dan-wanna-M) in [this commit](https://github.com/Dan-wanna-M/formatron/commit/4dc156fc9d6e30add389f34fc37ced9011fc8805).
N/A
**Examples**
N/A
N/A

Bump formatron to `0.4.11`

---

backends/exllamav2/model.py
common/config_models.py
config_sample.yml

with a setup of 3090+3060; loading 32b (5bpw) and 1.5b or 0.5b draft (6bpw) first loads the draft model and then the model; making an otherwise 32b fitting onto the single 3090 (a lot more bandwidth) leak onto the 3060 with quite a few layers, negating all benefits of the draft model and even dropping performance even more (15-30% less tps); now pinning the draft model to another gpu (the 3060) entirely bypasses that and you get the same performance boost for spec decoding as before.
tabby_config.yml example of a draft_gpu_split:
I have tested it both with autosplit on the target model and manually splitting via gpu_split, the gpu-split syntax stays the same to be able to re-use the same code.
this is merely a kick-off PR to make it work, as I'm not sure if there's anything else that …

add draft_gpu_split option for spec decoding

---

common/templating.py

Granite3 default template uses strftime_now function. 
Currently Jinja2 sandbox raises an exception because strftime_now is undefined and it disables /v1/chat/completions endpoint.
strftime_now is supported by [Transformers](https://huggingface.co/docs/transformers/chat_templating#callable-functions) and this change brings this functionality to TabbyAPI to ensure compatibility with Granite3 models and possibly with other models that might use this function.

Add strftime_now to Jinja2 to use with Granite3 models

---

endpoints/OAI/utils/chat_completion.py

This PR fixes the issue described in #301 where TabbyAPI fails with `TypeError: Object of type ToolCall is not JSON serializable` when processing responses from tool calls. This occurs during the second phase of the tool calling workflow when trying to render templates containing tool responses.
This fix is essential because it enables complete tool calling workflows in TabbyAPI. Without it, users can initiate tool calls but the server crashes when trying to process tool responses, making the entire tool calling feature unusable for real-world applications.
Before the fix: Tool calling fails after the first round of tool calls with:
```
TypeError: Object of type ToolCall is not JSON serializable
```
After the fix:
```python
tool_call_result = client.chat.completions.create( …
```

Fix Tool Call JSON Serialization Error

---

endpoints/OAI/utils/chat_completion.py

This PR fixes issue #306 where chat completion requests fail with a 503 error due to an `UnboundLocalError`. The error occurs in the `_create_response` function when the variable `finish_reason` is accessed before being initialized, specifically when no tool calls are present in the response.
This isn't a new feature but a critical bug fix. The current implementation causes all chat completion requests to fail when the response doesn't include tool calls. This fix ensures that the `finish_reason` variable is always initialized before it's used, preventing the server from crashing.
**Examples**
Before the fix:
```
UnboundLocalError: cannot access local variable 'finish_reason' where it is …
```

Bugfix: Chat completion requests fail with UnboundLocalError: finish_reason variable not initialized

---

backends/exllamav3/model.py

TypeError('unwrap() takes from 1 to 2 positional arguments but 3 were given')
Just a small fix.
**Examples**
It works.
There are already some more defaults (True) for this setting, so maybe falling back on another default is superfluous.

Model: fix add_bos_token

---

backends/exllamav2/model.py
backends/exllamav3/model.py
common/config_models.py
config_sample.yml
endpoints/OAI/types/chat_completion.py

Add support for cache quantization to the exllamav3 backend.
TODO:

Exllamav3 cache quantization

---

endpoints/OAI/utils/chat_completion.py

A recent refactor removed the `**kwargs` catch-all from model.container.generate(), replacing it with an explicit parameter list and renaming the former embeddings argument to mm_embeddings. The invocation in generate_tool_calls was overlooked and still supplies embeddings=… 
```
asyncio.create_task(
model.container.generate(
request_id,
pre_tool_prompt,
tool_data,
embeddings=mm_embeddings,
)
)
```
which would raise:
```
TypeError: generate() got an unexpected keyword argument 'embeddings'
```
This fixes this issue, tool calls should now be able to be generated again. I also aligned the variable name with the same variable in the `generate_chat_completion` function above
**Additional …

fix: Aligned Parameter Name in chat completions generate_tool_calls

---

backends/exllamav3/model.py

Gemma 3 works for me with `add_bos = True, encode_special_tokens = True` (as in [here](https://github.com/turboderp-org/exllamav3/blob/master/examples/chat.py#L103)), but right now it is explicitly `add_bos=False`, is this intended? That makes the generation broken with endless repetitions (same in the `chat.py` example, if I change it to `add_bos=False`).

Exl3: some models aren't functional without add_bos?

---

common/templating.py
docs/10.-Tool-Calling.md
endpoints/OAI/types/chat_completion.py
endpoints/OAI/types/tools.py
endpoints/OAI/utils/chat_completion.py
endpoints/OAI/utils/tools.py
templates/tool_calls/chatml_with_headers.jinja

Trims the extra variables from the tool calling implementation while still using template metadata as the primary source of truth for tokens (ex. tool_start).
Now, tool calling in TabbyAPI should be compatible with many more templates that follow the standard of using a tool_start token.

Streamline tool calling

---

common/config_models.py
config_sample.yml

cudaMallocAsync is now enabled by default on supported configurations as of 113643c0df73a52685c7fc54768307c6e06a051b.

Config: Remove developer arg cuda_malloc_backend

---

common/templating.py

Adds support for `chat_template.jinja`, the current default method for storing chat templates in latest `transformers`.

Templating: Support chat_template.jinja

---

backends/exllamav3/model.py

exl3 backend code is missing logprobs support
logprobs are very useful both for roleplay plebs for easy rerolling from the middle of the message (as well as for generally getting some very convenient info about what the model could have said instead), as well as for programmers using using models for classification (asking to reply with a single token and looking at probabilities).
**Examples**
The code is mostly copied from exl2 implementation. Works on my windows machine in a fresh installation; exl3 library does support logprobs via the same `return_top_tokens` arg.

add logprobs support for exl3
