theroyallab/tabbyAPI

config_sample.yml
main.py
model.py

Had to study the code to find out how to set 8bit cache and speculative sampling. I think it makes sense to have it in the config sample.

add cache_mode and draft_model_dir to config_sample.yml

---

TabbyAPI_Colab_Example.ipynb

Note that this uses wheels for python 3.10 and torch 2.1.0+cu118 which is the current default in colab

Add Colab example

---

TabbyAPI_Colab_Example.ipynb

make colab better, fix libcudart errors

---

.gitignore
Dockerfile
OAI/types/chat_completion.py
OAI/types/common.py
OAI/types/model.py
OAI/utils.py
README.md
Start.bat
auth.py
config_sample.yml
gen_logging.py
main.py
model.py
requirements-amd.txt
requirements-cu118.txt
requirements-nowheel.txt
requirements.txt
templates/README.md
templates/alpaca.jinja
templates/chatml.jinja
templating.py
tests/wheel_test.py
utils.py

This PR completely removes fastchat and replaces it with jinja2 and a replication of huggingface's chat template system. Also upgrade pydantic to version 2.x to upgrade to more modern methods of field customization.

Add new templates

---

docker-compose.yml

fschat has been removed from the Dockerfile a while ago.

Remove fschat from compose yaml

---

common/sampling.py

Adds dynatemp_low and dynatemp_high as aliases for min_temp and max_temp respectively. These are the parameter names used by SillyTavern.

Adds aliases for min_temp and max_temp

---

OAI/types/sampler_overrides.py
backends/exllamav2/grammar.py
backends/exllamav2/model.py
backends/exllamav2/utils.py
common/auth.py
common/config.py
common/gen_logging.py
common/logger.py
common/sampling.py
common/utils.py
main.py
requirements-amd.txt
requirements-cu118.txt
requirements-nowheel.txt
requirements.txt

This PR aims to improve the terminal-side appearance of Tabby.
- Use the Rich library for progress bars and other console-specific formatting enhancements
- Use loguru as an easy drop in replacement for various library logging
- Override Uvicorn's logger to use loguru via logging configs

Better appearance

---

common/logger.py

At the moment, you have to directly edit the logger file to change the level.

chore: make log level configurable via env variable

---

docker/Dockerfile

A clear and concise description of what the problem is. You can also link to an existing issue.
Dockerfile was outdated not resolved to work on pyproject.toml
An explanation of why the feature should be added. Please be as specific as possible to help us understand the reasoning.
People get the ability to work with Docker container easy setup
**Examples**
Examples of the feature in action and its significance compared to not having the feature.
```sh
docker compose -f docker/docker-compose.yml up -d
```
Add any other context or screenshots about the pull request here.

Dockerfile work with pyproject.toml

---

common/sampling.py
sampler_overrides/sample_preset.yml

* Add missing settings to sample_preset.yml
* Fix override for skip_special_tokens

Minor fixes for sampler override

---

backends/exllamav2/model.py
backends/exllamav2/utils.py
endpoints/OAI/types/model.py

N/A
Cleans up https://github.com/theroyallab/tabbyAPI/pull/121
**Examples**
N/A
N/A

Revision to paged attention checks

---

docker/docker-compose.yml

Solves https://github.com/theroyallab/tabbyAPI/issues/149
Because the current docker workflow is not running properly

Fix docker compose volume mount

---

endpoints/OAI/utils/chat_completion.py
endpoints/OAI/utils/completion.py

Simple Typo Fix

---

endpoints/OAI/utils/chat_completion.py

Removes two print statements within chat_completion.py. I assume these are from debugging and snuck in.

Remove rouge print statements within chat_completion.py

---

endpoints/core/router.py

The endpoint is broken causing issues in silly tavern

fix function arguments for get_model_list

---

common/tabby_config.py

Update tabby_config.py to fix issue #196
Fixes issue https://github.com/theroyallab/tabbyAPI/issues/196

Fix tabby_config.py _from_file

---

backends/exllamav2/model.py
backends/exllamav2/vision.py
common/config_models.py
common/multimodal.py
config_sample.yml
endpoints/OAI/router.py
endpoints/OAI/utils/chat_completion.py
endpoints/OAI/utils/completion.py
endpoints/core/router.py
endpoints/core/types/model.py
endpoints/core/types/token.py
pyproject.toml

N/A
Tracking issue: https://github.com/theroyallab/tabbyAPI/issues/235
**Examples**
N/A
To-do:
Future PRs:
- Accept image objects in completions - not sure if there is an accepted API standard for this
- Handle images in chat templates - there also isn't a standard for vision chat templates

Vision support

---

common/utils.py

Fix RoPE Ratio

---

backends/exllamav2/model.py
backends/exllamav3/model.py
common/config_models.py

Just copied some stuff around and it ended up working for basic use.
Exl3 implementation
Only if this is helpful.
**Examples**
Tested QwQ with SillyTavern. Reasoning, eos, gpu_split works.
I was bored and super eager to get this to work.

Exl3: Couldn't wait

---

common/logger.py

This pull request adds file based logging so that it can be easier to debug issues, or just review logs in general. There are a few configurable options, and I am open to suggestions.
An explanation of why the feature should be added. Please be as specific as possible to help us understand the reasoning.
**Examples**
Examples of the feature in action and its significance compared to not having the feature.
Add any other context or screenshots about the pull request here.

Add file based logging in addition to the normal console logs
